require("javier.packer")
require("javier.set")
require("javier.fzf")
require("javier.remap")
require("javier.colors")
require("javier.autocommands")
require("javier.leetcode")
require("javier.markdown")
